import type { Form7AFields } from "@/lib/ai/form7a";

export function Form7APreview({ form }: { form: Form7AFields }) {
  return (
    <div className="rounded-xl border border-slate-300 bg-white shadow-sm overflow-hidden font-serif text-slate-900">
      {/* Header */}
      <div className="border-b border-slate-200 bg-slate-50 px-6 py-4 text-center">
        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">
          Ontario Small Claims Court
        </p>
        <h2 className="text-base font-bold mt-0.5">Plaintiff&apos;s Claim</h2>
        <p className="text-xs text-slate-500 mt-0.5">Form 7A — O. Reg. 258/98</p>
      </div>

      <div className="px-6 py-5 space-y-5 text-sm">
        {/* Parties */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
              Plaintiff
            </p>
            <p className="font-medium">{form.plaintiff_name}</p>
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
              Defendant
            </p>
            <p className="font-medium">{form.defendant_name}</p>
            <p className="text-xs text-slate-500 mt-0.5">{form.defendant_address}</p>
          </div>
        </div>

        {/* Court + Amount */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
              Court Location
            </p>
            <p>{form.court_location}</p>
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
              Amount Claimed
            </p>
            <p className="font-bold text-base">
              ${Number(form.amount_claimed).toLocaleString("en-CA")} CAD
            </p>
          </div>
        </div>

        {/* Reasons for claim */}
        <div>
          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">
            Reasons for Claim and Details
          </p>
          <div className="space-y-3 text-sm leading-relaxed text-slate-800">
            {form.reasons_for_claim.map((para, i) => (
              <p key={i}>
                {para.text}
                {para.citation && (
                  <>
                    {" "}
                    <a
                      href={para.source_url ?? "#"}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-0.5 text-blue-600 font-medium text-xs hover:underline"
                    >
                      [{para.citation}]
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-2.5 w-2.5" fill="none"
                        viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round"
                          d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                      </svg>
                    </a>
                  </>
                )}
              </p>
            ))}
          </div>
        </div>

        {/* Relief sought */}
        <div>
          <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">
            Relief Sought
          </p>
          <ol className="space-y-1">
            {form.relief_sought.map((r, i) => (
              <li key={i} className="flex items-start gap-2 text-sm">
                <span className="text-slate-400">{i + 1}.</span>
                {r}
              </li>
            ))}
          </ol>
        </div>
      </div>

      <div className="border-t border-slate-100 bg-slate-50 px-6 py-3">
        <p className="text-[10px] text-slate-400 italic">
          Draft generated by Pro Se Helper. Review all citations with your lawyer before filing.
        </p>
      </div>
    </div>
  );
}
