import { ArrowUpRight, Check, CircleDot, Clock3, FileText } from "lucide-react";
import { useWorkspace } from "@/lib/workspace-context";

export function ClientPortal() {
  const { setClientPing, clientPing } = useWorkspace();

  const steps = [
    { state: "done" as const, date: "July 14 · 09:15 AM", title: "Matter File Intake Accepted", sub: "by Attorney Marcus Avery", note: "Engagement letter sent to sarah@drinkpure.com" },
    { state: "done" as const, date: "July 15 · 02:00 PM", title: "15-Minute Onboarding Consultation Completed", sub: "Recorded · summary auto-shared with client", note: "Scope agreed: vendor contract dispute, liquidated damages defense" },
    { state: "progress" as const, date: "July 16 · 11:30 AM", title: "Demand Letter Framework Generated by proseOS", sub: "Awaiting Attorney Signature", note: "Draft assembled from 4 prior PackCo precedents" },
    { state: "scheduled" as const, date: "Scheduled · est. July 18", title: "Formal Demand Package Delivery to Opposing Counsel", sub: "Certified mail + email · auto-tracked", note: "" },
  ];

  return (
    <div className="space-y-8">
      <div className="flex items-end justify-between">
        <div>
          <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.18em] text-ink-faint">
            <span className="grid h-4 w-4 place-items-center rounded-full bg-fog">
              <span className="h-1.5 w-1.5 rounded-full bg-success pulse-dot" />
            </span>
            Client transparency workspace · live
          </div>
          <h1 className="font-serif mt-3 text-[56px] leading-[0.98] tracking-tight">
            Matter Status:
            <span className="text-ink-soft"> DrinkPure vs. PackCo, Inc.</span>
          </h1>
          <p className="mt-3 max-w-2xl text-[14px] text-ink-soft">
            What Sarah Jenkins sees on her side. Every milestone, document, and clock — mirrored from the operations desk in real time.
          </p>
        </div>
        <div className="hidden text-right md:block">
          <div className="text-[11px] uppercase tracking-[0.18em] text-ink-faint">Matter ID</div>
          <div className="tabular mt-1 text-[14px]">DP-2025-0714</div>
        </div>
      </div>

      <div className="grid grid-cols-12 gap-6">
        <div className="col-span-12 lg:col-span-8">
          <div className="rounded-3xl border border-hairline bg-canvas p-8">
            <div className="flex items-center justify-between">
              <h3 className="text-[13px] font-medium">Proactive status timeline</h3>
              <span className="text-[11px] text-ink-faint">Updated 11:34 AM</span>
            </div>
            <ol className="relative mt-6 pl-1">
              <span aria-hidden className="absolute left-[10px] top-2 bottom-2 w-px bg-hairline" />
              {steps.map((s, i) => (
                <li key={i} className="relative grid grid-cols-12 gap-4 py-5">
                  <div className="col-span-12 flex items-start gap-4 md:col-span-4">
                    <StepDot state={s.state} />
                    <div>
                      <div className="text-[11px] uppercase tracking-[0.16em] text-ink-faint">
                        {s.state === "done" ? "✓ Verified" : s.state === "progress" ? "• In Progress" : "Scheduled"}
                      </div>
                      <div className="mt-1 text-[12px] tabular text-ink-soft">{s.date}</div>
                    </div>
                  </div>
                  <div className="col-span-12 md:col-span-8">
                    <div className={`text-[16px] leading-snug ${s.state === "scheduled" ? "text-ink-faint" : "text-ink"}`}>
                      {s.title}
                    </div>
                    <div className="mt-1 text-[12px] text-ink-soft">{s.sub}</div>
                    {s.note && (
                      <div className="mt-3 inline-flex items-center gap-2 rounded-md bg-fog px-2.5 py-1.5 text-[11px] text-ink-soft">
                        <FileText className="h-3 w-3" /> {s.note}
                      </div>
                    )}
                  </div>
                </li>
              ))}
            </ol>
            <div className="mt-6 flex items-center justify-between border-t border-hairline pt-5">
              <div className="text-[12px] text-ink-faint">
                Last attorney activity · <span className="text-ink-soft">Marcus Avery, 11 minutes ago</span>
              </div>
              <button
                onClick={() => setClientPing(true)}
                disabled={clientPing}
                className={`flex items-center gap-2 rounded-full border border-ink px-4 py-2 text-[12px] transition ${
                  clientPing ? "cursor-default border-success text-success" : "text-ink hover:bg-ink hover:text-canvas"
                }`}
              >
                {clientPing ? (
                  <>
                    <Check className="h-3.5 w-3.5" />
                    Update requested · attorney notified
                  </>
                ) : (
                  <>Request Proactive Status Update</>
                )}
              </button>
            </div>
          </div>
        </div>

        <div className="col-span-12 space-y-6 lg:col-span-4">
          <div className="rounded-3xl border border-hairline bg-canvas p-6">
            <h4 className="text-[13px] font-medium">Your team</h4>
            <div className="mt-4 space-y-3">
              {[
                { name: "Marcus Avery", role: "Lead attorney", initials: "MA" },
                { name: "Kira Avery", role: "Associate", initials: "KA" },
                { name: "proseOS", role: "Automation layer", initials: "OS" },
              ].map((p) => (
                <div key={p.name} className="flex items-center gap-3">
                  <div className={`grid h-9 w-9 place-items-center rounded-full text-[11px] font-medium ${p.initials === "OS" ? "bg-warm-mist text-ink" : "bg-fog text-ink-soft"}`}>
                    {p.initials}
                  </div>
                  <div>
                    <div className="text-[13px]">{p.name}</div>
                    <div className="text-[11px] text-ink-faint">{p.role}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-3xl border border-hairline bg-fog p-6">
            <h4 className="text-[13px] font-medium">Live spend</h4>
            <div className="mt-3 flex items-baseline gap-2">
              <span className="tabular font-serif text-[36px] leading-none">$1,840</span>
              <span className="text-[11px] text-ink-faint">of $4,200 retainer</span>
            </div>
            <div className="mt-3 h-1.5 w-full overflow-hidden rounded-full bg-canvas">
              <div className="h-full w-[44%] rounded-full bg-ink" />
            </div>
            <ul className="mt-5 space-y-2 text-[12px] text-ink-soft">
              <li className="flex justify-between"><span>Intake review</span><span className="tabular">$240</span></li>
              <li className="flex justify-between"><span>Onboarding call (15m)</span><span className="tabular">$0</span></li>
              <li className="flex justify-between"><span>Demand letter drafting</span><span className="tabular">$1,600</span></li>
            </ul>
          </div>

          <div className="rounded-3xl border border-hairline bg-canvas p-6">
            <h4 className="text-[13px] font-medium">Documents</h4>
            <ul className="mt-3 divide-y divide-hairline text-[13px]">
              {["Engagement letter.pdf", "Vendor contract — DrinkPure x PackCo.pdf", "Onboarding call summary.md"].map((d) => (
                <li key={d} className="flex items-center justify-between py-2.5 text-ink-soft hover:text-ink">
                  <span className="flex items-center gap-2 truncate"><FileText className="h-3.5 w-3.5 shrink-0" /> <span className="truncate">{d}</span></span>
                  <ArrowUpRight className="h-3.5 w-3.5 text-ink-faint" />
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

function StepDot({ state }: { state: "done" | "progress" | "scheduled" }) {
  if (state === "done")
    return (
      <span className="z-10 grid h-5 w-5 place-items-center rounded-full bg-ink text-canvas">
        <Check className="h-3 w-3" strokeWidth={3} />
      </span>
    );
  if (state === "progress")
    return (
      <span className="z-10 grid h-5 w-5 place-items-center rounded-full bg-warm-mist">
        <CircleDot className="h-3 w-3 text-ink" />
      </span>
    );
  return (
    <span className="z-10 grid h-5 w-5 place-items-center rounded-full border border-hairline bg-canvas">
      <Clock3 className="h-3 w-3 text-ink-faint" />
    </span>
  );
}
