/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as WorkspaceMattersRouteImport } from './routes/_workspace.matters'
import { Route as WorkspaceIntakeRouteImport } from './routes/_workspace.intake'
import { Route as WorkspaceCalendarRouteImport } from './routes/_workspace.calendar'
import { Route as WorkspaceBillingRouteImport } from './routes/_workspace.billing'
import { Route as WorkspaceClientIndexRouteImport } from './routes/_workspace.client/index'
import { Route as WorkspaceMattersMatterIdRouteImport } from './routes/_workspace.matters.$matterId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceMattersRoute = WorkspaceMattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceIntakeRoute = WorkspaceIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCalendarRoute = WorkspaceCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBillingRoute = WorkspaceBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceClientIndexRoute = WorkspaceClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceMattersMatterIdRoute =
  WorkspaceMattersMatterIdRouteImport.update({
    id: '/$matterId',
    path: '/$matterId',
    getParentRoute: () => WorkspaceMattersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/billing': typeof WorkspaceBillingRoute
  '/calendar': typeof WorkspaceCalendarRoute
  '/intake': typeof WorkspaceIntakeRoute
  '/matters': typeof WorkspaceMattersRouteWithChildren
  '/api/translate': typeof ApiTranslateRoute
  '/matters/$matterId': typeof WorkspaceMattersMatterIdRoute
  '/client/': typeof WorkspaceClientIndexRoute
}
export interface FileRoutesByTo {
  '/billing': typeof WorkspaceBillingRoute
  '/calendar': typeof WorkspaceCalendarRoute
  '/intake': typeof WorkspaceIntakeRoute
  '/matters': typeof WorkspaceMattersRouteWithChildren
  '/api/translate': typeof ApiTranslateRoute
  '/': typeof WorkspaceIndexRoute
  '/matters/$matterId': typeof WorkspaceMattersMatterIdRoute
  '/client': typeof WorkspaceClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/billing': typeof WorkspaceBillingRoute
  '/_workspace/calendar': typeof WorkspaceCalendarRoute
  '/_workspace/intake': typeof WorkspaceIntakeRoute
  '/_workspace/matters': typeof WorkspaceMattersRouteWithChildren
  '/api/translate': typeof ApiTranslateRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/matters/$matterId': typeof WorkspaceMattersMatterIdRoute
  '/_workspace/client/': typeof WorkspaceClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/calendar'
    | '/intake'
    | '/matters'
    | '/api/translate'
    | '/matters/$matterId'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/billing'
    | '/calendar'
    | '/intake'
    | '/matters'
    | '/api/translate'
    | '/'
    | '/matters/$matterId'
    | '/client'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/billing'
    | '/_workspace/calendar'
    | '/_workspace/intake'
    | '/_workspace/matters'
    | '/api/translate'
    | '/_workspace/'
    | '/_workspace/matters/$matterId'
    | '/_workspace/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/matters': {
      id: '/_workspace/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof WorkspaceMattersRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/intake': {
      id: '/_workspace/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof WorkspaceIntakeRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/calendar': {
      id: '/_workspace/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof WorkspaceCalendarRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/billing': {
      id: '/_workspace/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof WorkspaceBillingRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/client/': {
      id: '/_workspace/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof WorkspaceClientIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/matters/$matterId': {
      id: '/_workspace/matters/$matterId'
      path: '/$matterId'
      fullPath: '/matters/$matterId'
      preLoaderRoute: typeof WorkspaceMattersMatterIdRouteImport
      parentRoute: typeof WorkspaceMattersRoute
    }
  }
}

interface WorkspaceMattersRouteChildren {
  WorkspaceMattersMatterIdRoute: typeof WorkspaceMattersMatterIdRoute
}

const WorkspaceMattersRouteChildren: WorkspaceMattersRouteChildren = {
  WorkspaceMattersMatterIdRoute: WorkspaceMattersMatterIdRoute,
}

const WorkspaceMattersRouteWithChildren =
  WorkspaceMattersRoute._addFileChildren(WorkspaceMattersRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceBillingRoute: typeof WorkspaceBillingRoute
  WorkspaceCalendarRoute: typeof WorkspaceCalendarRoute
  WorkspaceIntakeRoute: typeof WorkspaceIntakeRoute
  WorkspaceMattersRoute: typeof WorkspaceMattersRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceClientIndexRoute: typeof WorkspaceClientIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceBillingRoute: WorkspaceBillingRoute,
  WorkspaceCalendarRoute: WorkspaceCalendarRoute,
  WorkspaceIntakeRoute: WorkspaceIntakeRoute,
  WorkspaceMattersRoute: WorkspaceMattersRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceClientIndexRoute: WorkspaceClientIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
